"""Format v4 prototype (native/src/v4.rs) against the Lean span model's test
vectors: `data/span-model-seed1-100.jsonl.gz`, generated by
`experiments/lean/Vectors.lean` (`vectors 100 1`) at 683d733 on branch
`bb/experiment-bend-2-for-the-key-index-s-delta-alge-thr_dqc6iaviun`; schema
in that branch's `experiments/lean/REPORT.md`, "Test vectors for the native
span code".

Each history's commits, endpoint births and retirements, and merges are
replayed through the native code. After every step: each span's kept
versions (newest first) and the predecessor on its oldest, per key; lookups
at the head and at each live endpoint; every `changes` class; every
read-ahead expectation.
"""

from __future__ import annotations

import gzip
import json
from pathlib import Path

import pytest
from solera import _native
from solera import keys as K

VECTORS = Path(__file__).parent / "data" / "span-model-seed1-100.jsonl.gz"
TINY = {"block_size": 16, "max_file_bytes": 48}  # a key's versions cross blocks and files
HEAD = 2**64 - 1
NAMES = {0: "added", 1: "updated", 2: "removed", 3: "nothing"}


def histories() -> list[dict]:
    with gzip.open(VECTORS, "rt") as f:
        return [json.loads(line) for line in f]


def blocks_of(files: list[bytes]) -> tuple[list[bytes], int]:
    out, codec = [], 1
    for data in files:
        footer = K.parse_footer(data[-K.FOOTER_SIZE :])
        tail = K.parse_tail(data[footer["filters_offset"] :], len(data))
        codec = tail["codec"]
        out += [data[off : off + size] for _, off, size, _, _ in tail["blocks"]]
    return out, codec


def contents(files: list[bytes]) -> dict[str, dict]:
    """A span's keys: versions newest first as [gen, del], the predecessor of the oldest."""

    out: dict[str, dict] = {}
    blocks, codec = blocks_of(files)
    for b in blocks:
        keys, gens, deleted, _, preds = K.decode_block(b, codec)
        for k, g, d, p in zip(keys, gens, deleted, preds, strict=True):
            e = out.setdefault(k.decode(), {"versions": [], "pred": None})
            e["versions"].append([g, bool(d)])
            e["pred"] = p  # the oldest version's comes last
    return out


class Replay:
    def __init__(self):
        self.spans: list[tuple[int, int, list[bytes]]] = []  # oldest first

    def runs(self, upto_gen: int | None = None, from_gen: int | None = None, gens=None):
        chosen = list(reversed(self.spans))
        got = [blocks_of(s[2]) for s in chosen]
        return [r[0] for r in got], [r[1] for r in got]

    def commit(self, step: dict) -> None:
        es = step["entries"]
        data = K.encode_file(
            [e["key"].encode() for e in es],
            [e["gen"] for e in es],
            bytes(e["del"] for e in es),
            predecessors=[e["pred"] for e in es],
        )
        files, _ = _native.merge_spans([blocks_of([data])[0]], [1], [], False, **TINY)
        self.spans.append((step["c"], step["c"], files))

    def merge(self, step: dict) -> None:
        ranges = [(i["a"], i["b"]) for i in step["inputs"]]
        lo = [(a, b) for a, b, _ in self.spans].index(ranges[0])
        group = self.spans[lo : lo + len(ranges)]
        assert [(a, b) for a, b, _ in group] == ranges
        runs = [blocks_of(s[2]) for s in reversed(group)]
        files, _ = _native.merge_spans(
            [r[0] for r in runs], [r[1] for r in runs], sorted(step["live"]), step["base"], **TINY
        )
        assert step["base"] == (group[0][0] == 0)
        self.spans[lo : lo + len(ranges)] = [(group[0][0], group[-1][1], files)]

    def check(self, state: dict, keys: list[str]) -> int:
        checks = 0
        # Spans, key by key.
        assert [(s["a"], s["b"]) for s in state["spans"]] == [(a, b) for a, b, _ in self.spans]
        for want, (_, _, files) in zip(state["spans"], self.spans, strict=True):
            assert contents(files) == want["keys"], want
            checks += len(want["keys"])
        runs, codecs = self.runs()
        bkeys = [k.encode() for k in keys]
        # Lookups.
        for bound, want in [(HEAD, state["lookup_head"])] + [
            (e["gen"], e["keys"]) for e in state["lookup_at"]
        ]:
            found, gens, deleted, _ = _native.span_lookup(runs, codecs, bkeys, bound)
            got = {
                k: (g if f and not d else None) for k, f, g, d in zip(keys, found, gens, deleted, strict=True)
            }
            assert got == want, (bound, got, want)
            checks += len(keys)
        # Changes, and the read-ahead rule on their output.
        for q in state["changes"]:
            ks, classes, gens, _, _, _, more = _native.span_changes(
                runs, codecs, None, None, 10**6, q["from_gen"], q["to_gen"]
            )
            assert not more
            got = {k.decode(): NAMES[c] for k, c in zip(ks, classes, strict=True)}
            assert got == q["classes"], (q, got)
            at_n = {k.decode(): (g, NAMES[c]) for k, c, g in zip(ks, classes, gens, strict=True)}
            for ra in (x for x in state["read_ahead"] if x["P"] == q["P"] and x["N"] == q["N"]):
                k = ra["key"]
                if k not in at_n or at_n[k][0] <= ra["r_gen"]:
                    mine = "skip"
                else:
                    # Changed after r: its class from the delivered state to its state at N.
                    live_n = at_n[k][1] in ("added", "updated")
                    mine = {(False, True): "added", (True, True): "updated", (True, False): "removed"}.get(
                        (ra["delivered"] == "live", live_n), "nothing"
                    )
                assert mine == ra["expected"], ra
                checks += 1
            checks += 1
        return checks


@pytest.mark.parametrize("history", histories(), ids=lambda h: f"h{h['history']}")
def test_native_spans_match_the_lean_model(history):
    r = Replay()
    for step in history["steps"]:
        if step["op"] == "commit":
            r.commit(step)
        elif step["op"] == "merge":
            r.merge(step)
        r.check(step["state"], history["keys"])
