"""Tabulate viewbench runs (runs/*.log, each ending in its JSON line) into
results.md: builds, reads, and dollars a month at one commit per 10 s.

    python3 bench/keys/views/report.py

Prices (checked 2026-10-04): S3 Standard, PUT $5 and GET $0.40 per million,
$0.023 per GB-month, in-region transfer free. Railway buckets, $0.015 per
GB-month, requests and bucket egress free, uploads from Railway services
billed as service egress, $0.05 per GB.

A month's reads: a consumer every commit reads 1 behind (259,200 times), an
hourly one 360 behind (720), a daily one 8,640 behind (30); writers'
lookups are the engine's warm cache (no GETs), or, on the "cold writer"
line, the measured cold `write` per commit.
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).parent
MONTH = 259_200
READS = {1: MONTH, 360: 720, 8640: 30}


def load() -> dict[str, dict]:
    out = {}
    for f in sorted((HERE / "runs").glob("*.log")):
        lines = [x for x in f.read_text().splitlines() if x.startswith("{")]
        if not lines:
            continue
        d = json.loads(lines[-1])
        if "built" in d:
            out[f.stem] = d
    return out


def dollars(d: dict) -> dict:
    b, reads = d["built"], {str(r["behind"]): r for r in d["reads"]}
    per = MONTH / b["commits"]
    puts = (b["delta_puts"] + b["merge_puts"]) * per
    gets = sum(reads[str(k)]["gets"] * n for k, n in READS.items() if str(k) in reads)
    gb = b["stored_mean_mb"] / 1e3
    up_gb = (b["delta_mb"] + b["merge_bytes"] / 1e6) * per / 1e3
    s3 = puts * 5e-6 + gets * 4e-7 + gb * 0.023
    cold = reads["write"]["gets"] * MONTH * 4e-7 if "write" in reads else 0
    return {"s3": s3, "s3_cold": s3 + cold, "railway": gb * 0.015 + up_gb * 0.05, "up_gb": up_gb, "puts": puts, "gets": gets}


def main():
    runs = load()
    out = ["# viewbench results", "", "Generated by `report.py` from `runs/*.log`.", ""]
    out += [
        "## Builds",
        "",
        "| Run | Stored, mean · peak · end (MB) | Background entry writes per entry committed | Background MB written | PUTs per commit | Drops | Build |",
        "|---|---|---|---|---|---|---|",
    ]
    for name, d in runs.items():
        b = d["built"]
        bg = b["merge_entries"] + b.get("pack_entries", 0)
        out.append(
            f"| {name} | {b['stored_mean_mb']:.0f} · {b['stored_peak_mb']:.0f} · {b['stored_end_mb']:.0f} | "
            f"{bg / b['delta_entries']:.2f} | {b['merge_bytes'] / 1e6:.0f} | "
            f"{(b['delta_puts'] + b['merge_puts']) / b['commits']:.2f} | {b['drops']} | {b['build_s'] / 60:.0f} min |"
        )
    out += ["", "## Reads (cold, isolated processes; mismatches against the fold)", ""]
    out += ["| Run | Read | Keys | First page | Full | GETs | MB | Peak RSS | Mismatches |", "|---|---|---|---|---|---|---|---|---|"]
    for name, d in runs.items():
        for r in d["reads"]:
            what = f"{r['behind']} behind" if isinstance(r["behind"], int) else r["behind"]
            if r["what"] == "full":
                what += " (dropped: full pass)"
            out.append(
                f"| {name} | {what} | {r['keys']:,} | {r['first_s']:.2f} s | {r['wall_s']:.2f} s | {r['gets']:,} | "
                f"{r['mb_in']:.1f} | {r['peak_mb']:.0f} MB | {r['mismatches']} |"
            )
    out += ["", "## Dollars a month (one commit per 10 s)", ""]
    out += ["| Run | S3, warm writer | S3, cold writer | Railway | of which uploads (GB) |", "|---|---|---|---|---|"]
    for name, d in runs.items():
        x = dollars(d)
        out.append(f"| {name} | ${x['s3']:.2f} | ${x['s3_cold']:.2f} | ${x['railway']:.3f} | {x['up_gb']:.1f} |")
    (HERE / "results.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
