"""Simulation runs that found a bug, replayed step for step: each a strict
xfail while its finding is open (docs/verification.md, "Findings"), an
ordinary test once fixed."""

import pytest

from .machine import Simulation
from .oracle import Violation
from .world import Fate


def test_f9_a_key_dropped_by_a_moved_output_leaves_its_consumers():
    """F9: `items` on the table store; `k10`, `k11` committed; `items` moves
    to FileStore (its first write there starts over, with an index of its
    own); the feed drops `k11`. `checks` (a per-key consumer) must drop it."""

    state = Simulation()
    state.boot(seed=2188, store="table")
    state.commit_feed(keys={"k10", "k11"}, op="upsert", version="1")
    state.redeploy(change="table", clean=True)
    state.commit_feed(keys={"k10", "k3", "k2"}, op="replace", version="1")
    state.teardown()


def test_f11_a_discard_entrys_delta_outlives_the_attempt_reading_it():
    """F11: a `copy` attempt's spec hands it clean up entry `delta` naming a
    delta file compaction let go of before the attempt was claimed; the
    entry is acknowledged meanwhile, and collection deleted that file while
    the attempt ran. The file is kept while an attempt holds the entry
    (docs/lifecycle.md §9.8; tests/server/test_model.py has the sequence
    itself). Timing-sensitive: the invariant checks between steps are part
    of the run."""

    state = Simulation()
    state.boot(seed=201, store="table")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.doom_next_worker(fate=Fate(kind="twice", seconds=30.0))
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.doom_next_worker(fate=Fate(kind="twice", seconds=3.0))
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.submit(asset="log", mode="full", partitions="latest", upstream=True)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.prune(keep=0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.prune(keep=0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_sites(op="upsert", site="west")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.store_weather(delay=15.0, error=0.02, lost=0.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.doom_next_worker(fate=Fate(kind="mute"))
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.prune(keep=0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.submit(asset="items", mode="incremental", partitions="all", upstream=True)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.cancel(newest=False)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.submit(asset="copy", mode="full", partitions="latest", upstream=False)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.cancel(newest=False)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k2"}, op="replace", version="1")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.doom_next_worker(fate=Fate(kind="mute"))
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_sites(op="upsert", site="east")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k0"}, op="replace", version="3")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_sites(op="upsert", site="east")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k1", "k2", "k0"}, op="replace", version="2")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.doom_next_worker(fate=Fate(kind="twice", seconds=3.0))
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k1", "k10", "k0"}, op="upsert", version="1")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_knob()
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.store_weather(delay=1.0, error=0.1, lost=0.02)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.doom_next_worker(fate=Fate(kind="mute"))
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.prune(keep=2)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_knob()
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.store_weather(delay=15.0, error=0.0, lost=0.1)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.doom_next_worker(fate=Fate(kind="mute"))
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.wait(seconds=45.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k11", "k3", "k2"}, op="upsert", version="3")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.wait(seconds=700.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.teardown()


def test_f12_a_rename_back_and_forth_over_rolling_deploys_keeps_up():
    """`copy` renamed to `mirror` and back over rolling deploys (the old
    engine runs on a minute): `mirror` ends holding `k1`, which `items`
    deleted while the name `mirror` was not served — the move of `copy`'s
    state onto a name that held state before keeps the old index under a
    position already past the deletion. Timing-sensitive: keep the steps."""

    state = Simulation()
    state.boot(store="file", seed=14094)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k3", "k11", "k1"}, op="replace", version="2")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k3", "k2"}, op="upsert", version="3")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k11"}, op="replace", version="3")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="rename", zombie=60.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="summary", zombie=60.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="rename", zombie=60.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k1"}, op="replace", version="2")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="rename", zombie=60.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k3"}, op="replace", version="3")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="rename", zombie=5.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k3", "k0"}, op="remove", version="1")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="summary", zombie=5.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="rename", zombie=0.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.teardown()


def test_f13_a_key_removed_after_a_store_move_leaves_its_consumers():
    """`items` on the table store holds `k11`; a clean redeploy, then a crash
    redeploy moving `items` to FileStore; the feed then removes `k11`.
    `copy` keeps `k11` (the deletion comes after the move)."""

    state = Simulation()
    state.boot(seed=225, store="table")
    state.commit_feed(keys={"k11"}, op="upsert", version="1")
    state.redeploy(change="summary", clean=True)
    state.redeploy(change="table", clean=False)
    state.commit_feed(keys={"k11", "k3"}, op="remove", version="1")
    state.teardown()


def test_f16_a_compaction_landing_after_a_commit_keeps_the_newest_entry():
    """F16: the feed removes every key of `items`; the compaction that
    empties `items`' index lands after a newer commit went to level 0;
    two more level-0 files are then moved into level 1 whole, overlapping,
    and a read finds an older entry: `items` keeps `k3` at its old value
    (in other runs, a key removed upstream, or an object already collected).
    The invariant checks between steps are part of the run."""

    state = Simulation()
    state.boot(seed=274, store="file")
    state.commit_feed(keys={"k2", "k0", "k1"}, op="upsert", version="2")
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.restart(clean=True, down=5.0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k0"}, op="replace", version="1")
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k10", "k0", "k1"}, op="remove", version="2")
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.restart(clean=False, down=120.0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k3", "k11", "k0"}, op="upsert", version="3")
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.restart(clean=True, down=5.0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.restart(clean=False, down=120.0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.teardown()


def test_f13_a_key_removed_after_a_takeover_moved_its_upstream_leaves_its_consumers():
    """F13 by another route, no crash: `k0`, `k11` committed; a takeover
    moves `items` from FileStore to the table store; the feed removes both.
    `copy` and `split`'s `odd` keep them; `checks` drops them."""

    state = Simulation()
    state.boot(seed=88, store="file")
    state.commit_feed(keys={"k11", "k0"}, op="replace", version="1")
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.commit_knob()
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.commit_knob()
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.store_weather(delay=1.0, error=0.0, lost=0.0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.takeover(change="table", zombie=0.0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.commit_feed(keys={"k11", "k0"}, op="remove", version="2")
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.teardown()


def test_f17_an_output_moved_away_and_back_keeps_its_keys():
    """F17: `items` holds `k10` on FileStore; a takeover moves it to the
    table store, where only a `keys=` run writes (a fresh index, the
    position unmoved); a takeover moves it back; the next write is a delta
    of `k3` and starts the index over again: `k10` is lost."""

    state = Simulation()
    state.boot(seed=88, store="file")
    state.commit_feed(keys={"k10"}, op="replace", version="1")
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.takeover(change="table", zombie=60.0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.wait(seconds=10.0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.submit(asset="items", keys=("k1", "k10"), mode="incremental", partitions="latest", upstream=True)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.takeover(change="table", zombie=0.0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.teardown()


def test_f34_a_rename_onto_an_earlier_lifes_name_keeps_its_attempt_settleable():
    """F34 (sweep Z11, replayable since the determinism fix): `copy` renamed
    to `mirror`; `mirror`'s attempt runs; `copy` comes back without an alias
    (`mirror` removed: a new life); `copy`'s attempt runs; `copy` is renamed
    to `mirror` again. The rename re-keys `copy`'s claim to `mirror` over
    the earlier life's, still running: the engine no longer finds that
    attempt's claim, cannot settle it, and its run never ends."""

    state = Simulation()
    state.boot(seed=0, store="file", cache=None)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.a_life_is_its_own()
    state.a_ticks_runs_are_submitted_once()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.index_spans_tile()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_attempt_per_partition()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="rename", zombie=0.0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.a_life_is_its_own()
    state.a_ticks_runs_are_submitted_once()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.index_spans_tile()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_attempt_per_partition()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.pool_hosts(hosts=0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.a_life_is_its_own()
    state.a_ticks_runs_are_submitted_once()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.index_spans_tile()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_attempt_per_partition()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.pool_hosts(hosts=0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.a_life_is_its_own()
    state.a_ticks_runs_are_submitted_once()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.index_spans_tile()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_attempt_per_partition()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.pool_hosts(hosts=0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.a_life_is_its_own()
    state.a_ticks_runs_are_submitted_once()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.index_spans_tile()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_attempt_per_partition()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change=None, zombie=0.0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.a_life_is_its_own()
    state.a_ticks_runs_are_submitted_once()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.index_spans_tile()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_attempt_per_partition()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="rename", zombie=0.0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.a_life_is_its_own()
    state.a_ticks_runs_are_submitted_once()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.index_spans_tile()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_attempt_per_partition()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="rename", zombie=0.0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.a_life_is_its_own()
    state.a_ticks_runs_are_submitted_once()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.index_spans_tile()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_attempt_per_partition()
    state.teardown()


@pytest.mark.xfail(strict=True, raises=Violation, reason="F38: open")
def test_f38_a_consumer_of_a_current_only_output_finishes_a_pass_its_upstream_outran():
    """F38 (sweep Z14): `items` lives in the table store, which holds its
    current rows only. `copy` is in a delta pass over `items`' commit 1
    (k1, k10, k2; batch 1 of 2 delivered) when `items`, its version bumped,
    rebuilds as commit 2 without k2. Batch 2 loads k2 by key: the store has
    no k2, so the load raises SourceBehind (F33's check) and retries. But
    the commit that removed k2 already exists, and the pass stays on commit
    1: every retry fails the same way, the budget runs out, and `copy`
    (and `checks`) stay stale for good."""

    state = Simulation()
    state.boot(seed=15510, store="table", cache=None)
    state.commit_feed(keys={"k10", "k2", "k1"}, op="upsert", version="3")
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.a_life_is_its_own()
    state.a_ticks_runs_are_submitted_once()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.index_spans_tile()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_attempt_per_partition()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.readd_live(clean=False, ends="succeeds")
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.a_life_is_its_own()
    state.a_ticks_runs_are_submitted_once()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.index_spans_tile()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_attempt_per_partition()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="bump", zombie=0.0)
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.a_life_is_its_own()
    state.a_ticks_runs_are_submitted_once()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.index_spans_tile()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_attempt_per_partition()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k11", "k1"}, op="replace", version="1")
    state.a_fenced_scope_at_rest_holds_its_index_keys()
    state.a_life_is_its_own()
    state.a_ticks_runs_are_submitted_once()
    state.committed_keys_are_readable()
    state.fenced_writes_hold_their_gate()
    state.index_spans_tile()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_attempt_per_partition()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.teardown()
