"""Simulation runs that found a bug, replayed step for step: each a strict
xfail while its finding is open (docs/verification.md, "Findings"), an
ordinary test once fixed. Open findings are not set aside here."""

import pytest

from .machine import Simulation
from .world import Fate


@pytest.fixture(autouse=True)
def unmasked(monkeypatch):
    monkeypatch.setenv("SOLERA_SIM_KNOWN", "1")


@pytest.mark.xfail(strict=True, reason="F9: a consumer keeps a key its upstream dropped when it moved store")
def test_f9_a_key_dropped_by_a_moved_output_leaves_its_consumers():
    """`items` on the table store; `k10`, `k11` committed; `items` moves to
    FileStore (its first write there starts over, with an index of its own);
    the feed drops `k11`. `checks` (an Each consumer) keeps `k11`."""

    state = Simulation()
    state.boot(seed=2188, store="table")
    state.commit_feed(keys={"k10", "k11"}, op="upsert", version="1")
    state.redeploy(change="table", clean=True)
    state.commit_feed(keys={"k10", "k3", "k2"}, op="replace", version="1")
    state.teardown()


def test_f11_a_discard_entrys_delta_outlives_the_attempt_reading_it():
    """F11: a `copy` attempt's spec hands it discard entry `delta` naming a
    delta file compaction let go of before the attempt was claimed; the
    entry is acknowledged meanwhile, and collection deleted that file while
    the attempt ran. The file is kept while an attempt holds the entry
    (docs/lifecycle.md §9.8; tests/server/test_model.py has the sequence
    itself). Timing-sensitive: the invariant checks between steps are part
    of the run."""

    state = Simulation()
    state.boot(seed=201, store="table")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.doom_next_worker(fate=Fate(kind="twice", seconds=30.0))
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.doom_next_worker(fate=Fate(kind="twice", seconds=3.0))
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.submit(asset="log", mode="full", partitions="latest", upstream=True)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.prune(keep=0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.prune(keep=0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_sites(op="upsert", site="west")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.store_weather(delay=15.0, error=0.02, lost=0.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.doom_next_worker(fate=Fate(kind="mute"))
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.prune(keep=0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.submit(asset="items", mode="incremental", partitions="all", upstream=True)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.cancel(newest=False)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.submit(asset="copy", mode="full", partitions="latest", upstream=False)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.cancel(newest=False)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k2"}, op="replace", version="1")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.doom_next_worker(fate=Fate(kind="mute"))
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_sites(op="upsert", site="east")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k0"}, op="replace", version="3")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_sites(op="upsert", site="east")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k1", "k2", "k0"}, op="replace", version="2")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.doom_next_worker(fate=Fate(kind="twice", seconds=3.0))
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k1", "k10", "k0"}, op="upsert", version="1")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_knob()
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.store_weather(delay=1.0, error=0.1, lost=0.02)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.doom_next_worker(fate=Fate(kind="mute"))
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.prune(keep=2)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_knob()
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.store_weather(delay=15.0, error=0.0, lost=0.1)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.doom_next_worker(fate=Fate(kind="mute"))
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.wait(seconds=45.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k11", "k3", "k2"}, op="upsert", version="3")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.wait(seconds=700.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.teardown()


@pytest.mark.xfail(
    strict=True,
    reason="F12: renames back and forth over rolling deploys leave a consumer a key deleted meanwhile",
)
def test_f12_a_rename_back_and_forth_over_rolling_deploys_keeps_up():
    """`copy` renamed to `mirror` and back over rolling deploys (the old
    engine runs on a minute): `mirror` ends holding `k1`, which `items`
    deleted while the name `mirror` was not served — the move of `copy`'s
    state onto a name that held state before keeps the old index under a
    watermark already past the deletion. Timing-sensitive: keep the steps."""

    state = Simulation()
    state.boot(store="file", seed=14094)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k3", "k11", "k1"}, op="replace", version="2")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k3", "k2"}, op="upsert", version="3")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k11"}, op="replace", version="3")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="rename", zombie=60.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="summary", zombie=60.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="rename", zombie=60.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k1"}, op="replace", version="2")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="rename", zombie=60.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k3"}, op="replace", version="3")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="rename", zombie=5.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.commit_feed(keys={"k3", "k0"}, op="remove", version="1")
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="summary", zombie=5.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.takeover(change="rename", zombie=0.0)
    state.committed_keys_are_readable()
    state.no_state_broke()
    state.nothing_read_after_collection()
    state.one_end_per_attempt()
    state.reads_say_what_they_read()
    state.teardown()
