"""Runnable laboratory fixture. All history in the UI is generated by real executions."""

from __future__ import annotations

import json
import os
from pathlib import Path

from data_orchestrator import (
    AssetContext,
    Automation,
    ByKey,
    CommitBatch,
    Cron,
    DailyPartitions,
    Definitions,
    Every,
    Inventory,
    OnCommit,
    Output,
    ReplaceKeys,
    asset,
)


@asset(group="Sources")
def source_files() -> Inventory:
    """Discover revisioned laboratory files from the editable local fixture."""
    path = Path(os.getenv("DORC_DEMO_SOURCE", "examples/lab_sources.json"))
    return Inventory(json.loads(path.read_text()), complete=True)


@asset(
    inputs={"files": "source_files"},
    group="Laboratory",
    outputs={
        "samples": Output(description="Sample identities with source-file provenance"),
        "measurements": Output(description="Assay measurements, replaced by source-file ownership"),
    },
    incremental=ByKey(input="files", batch_size=2),
)
def parse_files(ctx: AssetContext, files: Inventory) -> CommitBatch:
    """Parse only new or modified files; remove rows owned by deleted files."""
    changes = ctx.changes("files")
    samples, measurements = [], []
    for file in changes.upserted:
        for sample in file["samples"]:
            samples.append(
                {"source_file_id": file["id"], "sample_id": sample["id"], "site": sample["site"]}
            )
            for analyte, value in sample["assays"].items():
                measurements.append(
                    {
                        "source_file_id": file["id"],
                        "sample_id": sample["id"],
                        "analyte": analyte,
                        "value": value,
                    }
                )
    affected = (*changes.upserted_keys, *changes.deleted_keys)
    ctx.log("Parsed source changes", files=len(changes.upserted), deleted=len(changes.deleted_keys))
    return CommitBatch(
        outputs={
            "samples": ReplaceKeys("source_file_id", affected, samples),
            "measurements": ReplaceKeys("source_file_id", affected, measurements),
        },
        acknowledge=changes.token,
        metadata={"processed_files": len(changes.upserted)},
    )


@asset(group="Analytics")
def sample_summary(samples: list[dict], measurements: list[dict]) -> list[dict]:
    """Summarize measurement coverage for each source-owned sample."""
    return [
        {
            **sample,
            "assay_count": sum(
                m["sample_id"] == sample["sample_id"]
                and m["source_file_id"] == sample["source_file_id"]
                for m in measurements
            ),
        }
        for sample in samples
    ]


@asset(group="Analytics")
def sample_quality(sample_summary: list[dict]) -> list[dict]:
    """Flag samples whose measurement coverage needs attention."""
    return [
        {**sample, "quality": "complete" if sample["assay_count"] >= 3 else "review"}
        for sample in sample_summary
    ]


@asset(group="Sources", partitions=DailyPartitions("2026-01-01"))
def daily_observations(ctx: AssetContext) -> list[dict]:
    """Synthetic daily source fixture for exercising isolated partition backfills."""
    day = int(ctx.partition[-2:])
    return [
        {"day": ctx.partition, "instrument": instrument, "observations": day * 3 + index}
        for index, instrument in enumerate(["XRF-01", "XRF-02", "ICP-01"])
    ]


@asset(group="Analytics", partitions=DailyPartitions("2026-01-01"))
def daily_report(daily_observations: list[dict]) -> list[dict]:
    """Aggregate each day's observations independently of the live file cursor."""
    return [
        {
            "day": daily_observations[0]["day"],
            "instruments": len(daily_observations),
            "observations": sum(row["observations"] for row in daily_observations),
        }
    ]


definitions = Definitions(
    name="Laboratory",
    assets=[
        source_files,
        parse_files,
        sample_summary,
        sample_quality,
        daily_observations,
        daily_report,
    ],
    automations=[
        Automation("refresh_laboratory", ("sample_quality",), Every(300)),
        Automation("daily_reporting", ("daily_report",), Cron("0 6 * * *", "UTC")),
        Automation("quality_on_summary", ("sample_quality",), OnCommit(("sample_summary",))),
    ],
)
