"""Tables for docs/key-index-from-first-principles.md, from the replay logs
in `runs/` (each the output of one `model.py` invocation).

    python3 bench/keys/fp/report.py > bench/keys/fp/results.md
"""

from __future__ import annotations

import re
from pathlib import Path

RUNS = Path(__file__).parent / "runs"
HEAD = re.compile(r"^## ([\d,]+) keys, (.+) \((.+)\)$")
NUM = r"([\d.]+)"


def parse(path: Path) -> list[dict]:
    out, cur = [], None
    for line in path.read_text().splitlines():
        m = HEAD.match(line)
        if m:
            cur = {"keys": m.group(1), "scenario": m.group(2), "config": m.group(3), "reads": {}, "file": path.stem}
            out.append(cur)
            continue
        if cur is None:
            continue
        if line.startswith("runs "):
            g = lambda pat: re.search(pat, line).groups()
            cur["runs"], cur["runs_max"] = g(r"runs " + NUM + r" \((\d+)\)")
            cur["stored"], cur["stored_max"] = g(r"stored " + NUM + r" MB \((\d+)\)")
            cur["wb"], cur["we"] = g(r"writes " + NUM + r"x bytes, " + NUM + r"x entries")
            (cur["puts"],) = g(r"PUTs/commit " + NUM)
            (cur["up"],) = g(r"uploaded/commit " + NUM + " KB")
            cur["lg"], cur["lmb"], cur["ls"] = g(r"lookup " + NUM + r" GETs, " + NUM + r" MB, " + NUM + " s")
            cur["lfg"], cur["lfmb"], cur["lfs"] = g(r"filters held: " + NUM + r" GETs, " + NUM + r" MB, " + NUM + " s")
            (cur["per_key"],) = g(r"per live key " + NUM)
            (cur["full"],) = g(r"first run reads " + NUM + " MB")
        m = re.match(r"\s+(\d+) behind: reads " + NUM + r" MB = " + NUM + r"x needed \(max " + NUM + r"x\), runs "
                     + NUM + r" \((\d+)\), straddler " + NUM + r" MB, needed ([\d,]+)K keys", line)
        if m:
            d = int(m.group(1))
            cur["reads"][d] = dict(zip(["mb", "x", "xmax", "runs", "runs_max", "straddle", "need"], m.groups()[1:]))
    return out


def gets(r: dict) -> int:
    """A catch-up's GETs when the engine reads each run in >= 1 MB windows
    and serves consecutive batches from them: one per run, plus one per MB."""
    return round(float(r["runs"]) + float(r["mb"]))


def main() -> None:
    rows = [x for p in sorted(RUNS.glob("*.txt")) for x in parse(p)]
    print("# Replayed results (`model.py`)\n")
    print("Generated by `report.py` from `runs/*.txt`. One commit of 1K random keys per 10 s;")
    print("readers 1, 100, 360, 8,640 and 10,000 commits behind, plus 100 daily readers")
    print("(their positions matter only to the `floor` and `set` variants). Means over the")
    print("second half of each trace, sampled every 97th commit; maxima in parentheses.\n")
    print("## Structure, writes, head reads\n")
    print("| Log | Keys | Scenario | Config | Runs | Stored MB | Writes ×bytes · ×entries | PUTs/commit | KB uploaded/commit "
          "| Head entries per live key | Cold 1K lookup: GETs · MB · s | with filters held | First run MB |")
    print("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        print(f"| {r['file']} | {r['keys']} | {r['scenario']} | {r['config']} | {r['runs']} ({r['runs_max']}) | "
              f"{r['stored']} ({r['stored_max']}) | {r['wb']} · {r['we']} | {r['puts']} | {r['up']} | {r['per_key']} | "
              f"{r['lg']} · {r['lmb']} · {r['ls']} | {r['lfg']} · {r['lfmb']} · {r['lfs']} | {r['full']} |")
    print("\n## Catch-ups\n")
    print("Each cell: MB read · × the bytes of what changed (worst moment) · runs read (max) · GETs with 1 MB windows.\n")
    print("| Log | Keys | Scenario | Config | 1 behind | 100 behind | 360 behind | 8,640 behind | 10,000 behind |")
    print("|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        cells = []
        for d in (1, 100, 360, 8640, 10000):
            x = r["reads"].get(d)
            cells.append("—" if x is None else
                         f"{x['mb']} · {x['x']}× ({x['xmax']}×) · {x['runs']} ({x['runs_max']}) · {gets(x)}")
        print(f"| {r['file']} | {r['keys']} | {r['scenario']} | {r['config']} | " + " | ".join(cells) + " |")


if __name__ == "__main__":
    main()
